### ISSUE TITLE
why params only support int64? and how to convert go types to params such as string, slice

### ISSUE THREAD

**Issue by trainyao** [mathetake/gasm#12]
hello, got some questions.
maybe some example for other params can be added?

**Comment by tooolbox** [comment]
It's just the basic building block.

If you want to pas complex types in and out of the wasm VM, you have some hoops to jump through.  The way [rust-bindgen](https://github.com/rust-lang/rust-bindgen) does it is make a `malloc` method in the wasm, so you call `malloc(len int64) (ptr int64)` and then directly access the VM's memory at `ptr` and write your stuff, and then call `readString(ptr, len int64)` or something to tell the wasm to read from the memory you just wrote.

It's really a communication layer that needs to be added by whatever's compiling the wasm.
