### ISSUE TITLE
CNCF SIG-Runtime Discussion/Presentation

### ISSUE THREAD

**Issue by raravena80** [mathetake/gasm#19]
Hello Gasm team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I'm reaching out and think it would be great for you to present/discuss the project at one of our meetings. For example, discuss things such as architecture overview and use cases.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by mathetake** [comment]
Hi @raravena80, I am sorry but I don't have any motivation to talk about gasm there since this is just my personal toy project, and I don't have any plan to maintain this repository right now. Thanks for reaching out :smile:
